config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  namespace :admin do
    resources :tenants, only: %i[new create index show] do
      resources :products
      resources :orders, only: %i[index show]
    end
    get 'dashboard', to: 'dashboard#index'
  end
  get  '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :shops, only: %i[index show], param: :tenant_id do
    resources :orders, only: %i[new create show]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Nexus Market" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application" %>
  </head>

  <nav style="padding:10px; border-bottom:1px solid #ddd; display: flex; justify-content: space-between; align-items: center;">
    <% if current_user %>
    <div>
      <% if current_user.customer? %>
        <%= link_to "← Back to Shops", shops_path, class: "btn btn-secondary btn-sm" %>
      <% else %>
        <%= link_to "← Back to Tenants", admin_tenants_path, class: "btn btn-secondary btn-sm" %>
      <% end %>
    </div>
      <span>
        Logged in as <strong><%= current_user.email %></strong> [<%= current_user.role %>]
      </span>

      <%= form_with url: logout_path, method: :delete, local: true, style: "display:inline;" do %>
        <%= submit_tag "Logout", style: "margin-left:10px;" %>
      <% end %>
    <% end %>
  </nav>

  <body>
    <%= yield %>
  </body>
</html>